#!/bin/bash
#
# $Id$
#
### BEGIN INIT INFO
# Provides: patched
# Short-Description: This is a web/api for the Patched configuration manager.
# Description: This is a web/api to interface with the Patched configuration manager.
### END INIT INFO

# chkconfig: 345 99 99

. /etc/init.d/functions
. /etc/sysconfig/network

PIDFILE="/opt/Patched/pids/agent.pid"
prog="patched"
exec="/opt/Patched/docroot/patched/script/patched"

start() {
    if [ "$NETWORKING" = "no" ]; then
        echo -n $"Networking doesn't seem to be configured:"
        failure $"Networking doesn't seem to be configured:"
        echo
        return 1
    fi

    pidofproc -p "$PIDFILE" "$exec" > /dev/null
    if [ "0" -eq "$?" ]; then
        echo -n $"Patched is running:"
        warning $"Patched is running:"
        echo
        return 1
    fi

	echo -n $"Starting Patched web/api: "
    cd /opt/Patched/docroot/patched
    nohup /opt/Patched/perl $exec daemon -l 'http://*:6000' > /dev/null 2>/dev/null &
    RETVAL=$?

    if [ "0" -eq "$RETVAL" ]; then
        success $"Patched started:"
        echo
        return 0
    else
        failure $"Patched not started:"
        echo
        return $RETVAL
    fi
}

stop() {
	echo -n $"Shutting down Patched: "
    killproc -p "$PIDFILE" $exec
    RETVAL=$?
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p "$PIDFILE" -l $prog $exec
	;;
  restart|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload}"
	exit 2
esac

exit $?
