#!/bin/bash
#
# $Id$
#
### BEGIN INIT INFO
# Provides: patched
# Short-Description: This is a web/api for the Patched configuration manager.
# Description: This is a web/api to interface with the Patched configuration manager.
### END INIT INFO

# chkconfig: 345 99 99

. /etc/init.d/functions

start() {
	# Check that networking is configured.
	[ ${NETWORKING} = "no" ] && exit 1

	echo -n $"Starting Patched web/api: "
    daemon /opt/Patched/perl/bin/perl /opt/Patched/patched.pl daemon -l 'http://*:6000'
    RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down router discovery services: "
	if [ $UID -ne 0 ]; then
                RETVAL=4
                failure
        else
        	killproc /sbin/rdisc
		RETVAL=$?
	        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        fi;
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status rdisc
	;;
  restart|reload)
	restart
	;;
  condrestart)
	if status $prog > /dev/null; then
	    stop
	    start
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload}"
	exit 2
esac

exit $?
