#!/bin/bash
#
# $Id$
#
### BEGIN INIT INFO
# Provides: patched
# Short-Description: This is a web/api for the Patched configuration manager.
# Description: This is a web/api to interface with the Patched configuration manager.
### END INIT INFO

# chkconfig: 345 99 99

. /etc/init.d/functions

PIDFILE="/opt/Patched/pids/agent.pid"
prog="patched"
exec="/opt/Patched/docroot/patched/script/patched"

start() {
	# Check that networking is configured.
	[ ${NETWORKING} = "no" ] && exit 1

	echo -n $"Starting Patched web/api: "
    daemon --pidfile="$PIDFILE" /opt/Patched/perl/bin/perl $exec daemon -l 'http://*:6000'
    RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down Patched: "
    killproc -p "$PIDFILE" $exec
    RETVAL=$?
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

RETVAL=0

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p "$PIDFILE" -l $prog $exec
	;;
  restart|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload}"
	exit 2
esac

exit $?
